### ISSUE TITLE
Flagged by VirusTotal

### ISSUE THREAD

**Issue by nesper8** [YuriSizuku/Kirikiroid2Yuri#2]
Scanning on VirusTotal gives out 15/65 detection
https://www.virustotal.com/gui/file/782d85ed767ec8c07d69709b668275f3872ae6472b02343038538f011337c83d

Would be cool if you could correct this problem

**Comment by YuriSizuku** [comment]
This might because of the modifty of the apk is by reverse project. 
I will then try to develop and compile from souce.  It is a hard work to collect all of the dependencies. 
Sooner of later the new release will solve this problem.

**Comment by nesper8** [comment]
Thank you
