### ISSUE TITLE
Updates from another no longer developed fork

### ISSUE THREAD

**Issue by nesper8** [YuriSizuku/Kirikiroid2Yuri#4]
While going through the list of forks for kirikiroid2, I came across this fork with some updates but unfortunately also stopped development 
https://github.com/ningshanwutuobang/Kirikiroid2
Do you think it's possible to to import some code if it's up to your standards

**Comment by YuriSizuku** [comment]
I refered some of the code from this repo. This repo meets the same problem I mentioned in the issue.
